library("swirl")
library("swirlify")

setwd("~/Documents/R_scripts/Swirl_Cource/RBasic/")
# new_lesson("Intro", "DSC2015")
# new_lesson("Learn_Swirl", "DSC2015")
# new_lesson("RBasic")
set_lesson("DSC2015/Intro/lesson.yaml")
set_lesson("DSC2015/Learn_Swirl/lesson.yaml")
set_lesson("DSC2015/RBasic/lesson.yaml")
zip_course("DSC2015", ".")
system("cp swirl_zip_creator_TEMP/DSC2015.zip ./ && rm -rf swirl_zip_creator_TEMP")
uninstall_course("DSC2015")
install_course_zip("DSC2015.zip")
swirl()
