library("swirl")
library("swirlify")

setwd("~/Documents/R_scripts/Swirl_Cource/RBasic/")
# new_lesson("Intro", "DSC2015")
# new_lesson("Learn_Swirl", "DSC2015")
# new_lesson("RBasic_Part_1:_Simple_Data_Analysis", "DSC2015")
# new_lesson("RBasic_Part_2:_Data_Structure_in_R", "DSC2015")
# new_lesson("RBasic_Part_3:_Basic_Operations", "DSC2015")
# new_lesson("RBasic_Part_4:_Loops_and_Control_Flow", "DSC2015")
set_lesson("DSC2015/Intro/lesson.yaml")
set_lesson("DSC2015/Learn_Swirl/lesson.yaml")
set_lesson("DSC2015/RBasic_Part_1:_Simple_Data_Analysis/lesson.yaml")
set_lesson("DSC2015/RBasic_Part_2:_Data_Structure_in_R/lesson.yaml")
set_lesson("DSC2015/RBasic_Part_3:_Basic_Operations/lesson.yaml")
set_lesson("DSC2015/RBasic_Part_4:_Loops_and_Control_Flow/lesson.yaml")
zip_course("DSC2015", ".")
system("cp swirl_zip_creator_TEMP/DSC2015.zip ./ && rm -rf swirl_zip_creator_TEMP")
uninstall_course("DSC2015")
install_course_zip("DSC2015.zip")
delete_progress("dboy")
swirl()
